apiVersion: batch/v1
kind: Job
metadata:
  name: { { job_name } }
  namespace: { { namespace } }
  labels:
    app: dcc-runtime
    managed-by: oom-scheduler
    oom/artist: { { username } }

spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: dcc-runtime
        managed-by: oom-scheduler
        oom/artist: { { username } }
        oom-pdg-service: { { job_name } }

    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: dcc-scheduler
      restartPolicy: Never
      priorityClassName: farm-default
      dnsPolicy: ClusterFirstWithHostNet

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: oom/farm
                    operator: In
                    values:
                      - "true"

      volumes:
        # PVCs
        - name: node-dev
          persistentVolumeClaim:
            claimName: node-dev-pvc
        # HostPaths
        - name: raid
          hostPath:
            path: /mnt/RAID
            type: Directory
        - name: home
          hostPath:
            path: /home
            type: Directory
        - name: passwd
          hostPath:
            path: /etc/passwd
            type: File
        - name: group
          hostPath:
            path: /etc/group
            type: File

      containers:
        - name: service
          image: "ghcr.io/sneakyfoot/dcc-runtime:{ { OOM_TAG | default('latest') } }"
          imagePullPolicy: Always

          command:
            - /bin/bash
          args:
            - -lc
            - { { command } }

          env:
            - name: OOM_DEV
              value: { { oom_dev } }
            - name: NODE_DEV
              value: /opt/node_dev
            - name: OCIO
              value: /mnt/RAID/Assets/studio-config-v2.2.0_aces-v1.3_ocio-v2.3.ocio
            - name: HOUDINI_OCL_DEVICETYPE
              value: CPU
            - name: HOUDINI_OCL_VENDOR
              value: Intel(R) Corporation
            - name: OPENCL_VENDOR_PATH
              value: /etc/OpenCL/vendors
            - name: OOM_PROJECT_ID
              value: "{ { OOM_PROJECT_ID } }"
            - name: OOM_PROJECT_PATH
              value: { { OOM_PROJECT_PATH } }
            - name: OOM_SEQUENCE_ID
              value: "{ { OOM_SEQUENCE_ID } }"
            - name: OOM_SHOT_ID
              value: "{ { OOM_SHOT_ID } }"
            - name: OOM_SHOT_PATH
              value: { { OOM_SHOT_PATH } }
            - name: CUT_IN
              value: "{ { CUT_IN } }"
            - name: CUT_OUT
              value: "{ { CUT_OUT } }"

          securityContext:
            runAsUser: { { uid } }
            runAsGroup: { { gid } }

          volumeMounts:
            # PVCs
            - name: node-dev
              mountPath: /opt/node_dev
            # HostPaths
            - name: raid
              mountPath: /mnt/RAID
              readOnly: false
            - name: home
              mountPath: /home
              readOnly: false
            - name: passwd
              mountPath: /etc/passwd
              readOnly: true
            - name: group
              mountPath: /etc/group
              readOnly: true
